version: '3.8'

services:
  seaweedfs:
    container_name: myapp_seaweedfs
    image: chrislusf/seaweedfs:latest
    ports:
      - "8333:8333"
      - "9333:9333"
    command: 'server -s3 -dir=/data'
    volumes:
      - seaweed_data:/data
    networks:
      - s3_net
    restart: unless-stopped

networks:
  s3_net:
    driver: bridge

volumes:
  seaweed_data: